/*
 * Copyright 2017 Kwoksys
 *
 * http://www.kwoksys.com/LICENSE
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.kwoksys.test.cases;

import com.kwoksys.framework.http.RequestContext;
import com.kwoksys.test.cases.KwokTestCase;
import com.kwoksys.test.utils.HttpHelper;

/**
 * UiRequestTest class.
 */
public class UrlRequestTest extends KwokTestCase {

    private boolean start = true;

    public static void main(String[] args) throws Exception {
        UrlRequestTest test = new UrlRequestTest(new RequestContext());
        test.execute();
    }

    public UrlRequestTest(RequestContext requestContext) {
        super(requestContext);
    }

    public void execute() throws Exception {
        httpget("admin/attribute-detail.htm?attributeId=-16");
        httpget("admin/attribute-edit.htm?attributeId=-16");
        httpget("admin/attribute-edit-2.htm");
        httpget("admin/attribute-field-add.htm?attributeId=-16");
        httpget("admin/attribute-field-add-2.htm");
        httpget("admin/attribute-field-edit.htm?attrFieldId=48");
        httpget("admin/attribute-field-edit-2.htm");
        httpget("admin/attribute-group-add.htm?objectTypeId=4");
        httpget("admin/attribute-group-add-2.htm");
        httpget("admin/attribute-group-delete.htm?objectTypeId=2&attrGroupId=1");
        httpget("admin/attribute-group-delete-2.htm");
        httpget("admin/attribute-group-edit.htm?objectTypeId=2&attrGroupId=1");
        httpget("admin/attribute-group-edit-2.htm");
        httpget("admin/attribute-list.htm");
        httpget("admin/config.htm");
        httpget("admin/config-edit-2.htm");
        httpget("admin/config-write.htm");
        httpget("admin/cust-attr.htm");
        httpget("admin/cust-attr-add.htm?objectTypeId=4");
        httpget("admin/cust-attr-add-2.htm");
        httpget("admin/cust-attr-delete.htm?attrId=2");
        httpget("admin/cust-attr-delete-2.htm");
        httpget("admin/cust-attr-detail.htm?attrId=2");
        httpget("admin/cust-attr-edit.htm?attrId=2");
        httpget("admin/cust-attr-edit-2.htm");
        httpget("admin/data-import-execute.htm");
        httpget("admin/data-import-index.htm");
        httpget("admin/data-import-results.htm");
        httpget("admin/data-import-validate.htm");
        httpget("admin/group-access.htm?groupId=2");
        httpget("admin/group-access-edit.htm?groupId=2");
        httpget("admin/group-access-edit-2.htm");
        httpget("admin/group-add.htm");
        httpget("admin/group-add-2.htm");
        httpget("admin/group-delete.htm?groupId=2");
        httpget("admin/group-delete-2.htm");
        httpget("admin/group-detail.htm?groupId=2");
        httpget("admin/group-edit.htm?groupId=2");
        httpget("admin/group-edit-2.htm");
        httpget("admin/group-list.htm");
        httpget("admin/index.htm");
        httpget("admin/user-access.htm?userId=13");
        httpget("admin/user-access-edit.htm?userId=13");
        httpget("admin/user-access-edit-2.htm");
        httpget("admin/user-add.htm");
        httpget("admin/user-add-2.htm");
        httpget("admin/user-delete.htm?userId=13");
        httpget("admin/user-delete-2.htm");
        httpget("admin/user-detail.htm?userId=13");
        httpget("admin/user-edit.htm?userId=13");
        httpget("admin/user-edit-2.htm");
        httpget("admin/user-hardware.htm?userId=13");
        httpget("admin/user-index.htm");
        httpget("admin/user-list.htm");
        httpget("admin/user-list-export.htm");
        httpget("admin/user-pw-reset.htm?userId=13");
        httpget("admin/user-pw-reset-2.htm");
        httpget("blogs/category-add.htm");
        httpget("blogs/category-add-2.htm");
        httpget("blogs/category-edit.htm?categoryId=1");
        httpget("blogs/category-edit-2.htm");
        httpget("blogs/category-list.htm");
        httpget("blogs/index.htm");
        httpget("blogs/post-add.htm");
        httpget("blogs/post-add-2.htm");
        httpget("blogs/post-comment-add-2.htm");
        httpget("blogs/post-delete.htm?postId=9");
        httpget("blogs/post-delete-2.htm");
        httpget("blogs/post-detail.htm?postId=9");
        httpget("blogs/post-edit.htm?postId=16");
        httpget("blogs/post-edit-2.htm");
        httpget("blogs/post-list.htm");
        httpget("blogs/post-list-rss.htm");
        httpget("contacts/company-add.htm");
        httpget("contacts/company-add-2.htm");
        httpget("contacts/company-bookmark.htm?companyId=9");
        httpget("contacts/company-bookmark-add.htm?companyId=9");
        httpget("contacts/company-bookmark-add-2.htm");
        httpget("contacts/company-bookmark-delete-2.htm");
        httpget("contacts/company-bookmark-edit.htm?companyId=9&bookmarkId=8");
        httpget("contacts/company-bookmark-edit-2.htm");
        httpget("contacts/company-contact.htm?companyId=9");
        httpget("contacts/company-contact-add.htm?companyId=9");
        httpget("contacts/company-contact-add-2.htm");
        httpget("contacts/company-contact-delete.htm?companyId=9");
        httpget("contacts/company-contact-delete-2.htm");
        httpget("contacts/company-contact-edit.htm?contactId=27");
        httpget("contacts/company-contact-edit-2.htm");
        httpget("contacts/company-contact-export.htm?companyId=9");
        httpget("contacts/company-contracts.htm?companyId=9");
        httpget("contacts/company-delete.htm?companyId=9");
        httpget("contacts/company-delete-2.htm");
        httpget("contacts/company-detail.htm?companyId=9");
        httpget("contacts/company-edit.htm?companyId=9");
        httpget("contacts/company-edit-2.htm");
        httpget("contacts/company-file.htm?companyId=9");
        httpget("contacts/company-file-add.htm?companyId=9");
        httpget("contacts/company-file-add-2.htm");
        httpget("contacts/company-file-delete.htm");
        httpget("contacts/company-file-delete-2.htm");
        httpget("contacts/company-file-download.htm");
        httpget("contacts/company-issue.htm?companyId=9");
        httpget("contacts/company-issue-add.htm?companyId=9");
        httpget("contacts/company-issue-add-2.htm");
        httpget("contacts/company-issue-remove-2.htm");
        httpget("contacts/company-list.htm");
        httpget("contacts/company-list-export.htm");
        httpget("contacts/company-note.htm?companyId=9");
        httpget("contacts/company-note-add.htm?companyId=9");
        httpget("contacts/company-note-add-2.htm");
        httpget("contacts/contact-add.htm");
        httpget("contacts/contact-add-2.htm");
        httpget("contacts/contact-delete.htm?contactId=28");
        httpget("contacts/contact-delete-2.htm");
        httpget("contacts/contact-detail.htm?contactId=28");
        httpget("contacts/contact-detail-vcard.htm?contactId=28");
        httpget("contacts/contact-edit.htm?contactId=28");
        httpget("contacts/contact-edit-2.htm");
        httpget("contacts/contact-list.htm");
        httpget("contacts/index.htm");
        httpget("contracts/contact-add.htm?contractId=9");
        httpget("contracts/contact-add-2.htm");
        httpget("contracts/contact-remove-2.htm");
        httpget("contracts/contacts.htm?contractId=9");
        httpget("contracts/custom-fields.htm?contractId=9");
        httpget("contracts/item-list.htm?contractId=9");
        httpget("contracts/software-add.htm?contractId=9");
        httpget("contracts/software-add-2.htm");
        httpget("contracts/software-remove-2.htm");
        httpget("hardware/ajax-get-component-custom-fields.htm?hardwareId=25&compId=3");
        httpget("hardware/contact-add.htm?hardwareId=25");
        httpget("hardware/contact-add-2.htm");
        httpget("hardware/contact-remove.htm?hardwareId=25&contactId=5");
        httpget("hardware/contacts.htm?hardwareId=25");
        httpget("hardware/custom-fields.htm?hardwareId=25");
        httpget("hardware/hardware-member.htm?hardwareId=25");
        httpget("hardware/hardware-member-add.htm?hardwareId=25");
        httpget("hardware/hardware-member-add-2.htm");
        httpget("hardware/hardware-member-remove.htm?hardwareId=25&formHardwareId=2");
        httpget("home/index.htm");
        httpget("issue-plugin/issue-add.htm");
        httpget("issue-plugin/issue-add-2.htm");
        httpget("issue-plugin/issue-add-3.htm");
        httpget("issues/index.htm");
        httpget("issues/add.htm");
        httpget("issues/add-2.htm");
        httpget("issues/detail.htm?issueId=14");
        httpget("issues/edit.htm?issueId=14");
        httpget("issues/edit-2.htm");
        httpget("issues/file-add.htm?issueId=14");
        httpget("issues/file-add-2.htm");
        httpget("issues/file-download.htm");
        httpget("issues/list.htm");
        httpget("issues/list-export.htm");
        httpget("issues/issue-delete.htm?issueId=14");
        httpget("issues/issue-delete-2.htm");
        httpget("issues/issue-relationship.htm?issueId=14");
        httpget("IT/ajax-get-hardware-detail.htm");
        httpget("IT/ajax-get-license-by-software.htm");
        httpget("IT/ajax-get-software-by-maker.htm");
        httpget("contracts/add.htm");
        httpget("contracts/add-2.htm");
        httpget("contracts/delete.htm?contractId=9");
        httpget("contracts/delete-2.htm");
        httpget("contracts/detail.htm?contractId=9");
        httpget("contracts/edit.htm?contractId=9");
        httpget("contracts/edit-2.htm");
        httpget("contracts/file-add.htm?contractId=9");
        httpget("contracts/file-add-2.htm");
        httpget("contracts/file-delete.htm");
        httpget("contracts/file-delete-2.htm");
        httpget("contracts/file-download.htm");
        httpget("contracts/hardware-add.htm?contractId=9");
        httpget("contracts/hardware-add-2.htm");
        httpget("contracts/hardware-remove-2.htm");
        httpget("contracts/index.htm");
        httpget("contracts/list.htm");
        httpget("hardware/add.htm");
        httpget("hardware/add-2.htm");
        httpget("hardware/comp.htm?hardwareId=25");
        httpget("hardware/comp-add.htm?hardwareId=25");
        httpget("hardware/comp-add-2.htm");
        httpget("hardware/comp-delete-2.htm");
        httpget("hardware/comp-edit.htm?hardwareId=25&compId=3");
        httpget("hardware/comp-edit-2.htm");
        httpget("hardware/delete.htm?hardwareId=25");
        httpget("hardware/delete-2.htm");
        httpget("hardware/detail.htm?hardwareId=25");
        httpget("hardware/edit.htm?hardwareId=25");
        httpget("hardware/edit-2.htm");
        httpget("hardware/file.htm?hardwareId=25");
        httpget("hardware/file-add.htm?hardwareId=25");
        httpget("hardware/file-add-2.htm");
        httpget("hardware/file-delete.htm");
        httpget("hardware/file-delete-2.htm");
        httpget("hardware/file-download.htm");
        httpget("hardware/index.htm");
        httpget("hardware/issue.htm?hardwareId=25");
        httpget("hardware/issue-add.htm?hardwareId=25");
        httpget("hardware/issue-add-2.htm");
        httpget("hardware/issue-remove-2.htm");
        httpget("hardware/license-add.htm?hardwareId=25");
        httpget("hardware/license-add-2.htm");
        httpget("hardware/license-remove-2.htm");
        httpget("hardware/list.htm");
        httpget("hardware/list-export.htm");
        httpget("software/add.htm");
        httpget("software/add-2.htm");
        httpget("software/bookmark.htm?softwareId=15");
        httpget("software/bookmark-add.htm?softwareId=15");
        httpget("software/bookmark-add-2.htm");
        httpget("software/bookmark-delete.htm?softwareId=15&bookmarkId=9");
        httpget("software/bookmark-delete-2.htm");
        httpget("software/bookmark-edit.htm?softwareId=15&bookmarkId=9");
        httpget("software/bookmark-edit-2.htm");
        httpget("software/delete.htm?softwareId=15");
        httpget("software/delete-2.htm");
        httpget("software/detail.htm?softwareId=15");
        httpget("software/edit.htm?softwareId=15");
        httpget("software/edit-2.htm");
        httpget("software/file.htm?softwareId=15");
        httpget("software/file-add.htm?softwareId=15");
        httpget("software/file-add-2.htm");
        httpget("software/file-delete.htm");
        httpget("software/file-delete-2.htm");
        httpget("software/file-download.htm");
        httpget("software/index.htm");
        httpget("software/issue.htm?softwareId=15");
        httpget("software/issue-add.htm?softwareId=15");
        httpget("software/issue-add-2.htm");
        httpget("software/issue-remove-2.htm");
        httpget("software/license-add.htm?softwareId=15");
        httpget("software/license-add-2.htm");
        httpget("software/license-delete.htm?softwareId=15&licenseId=301");
        httpget("software/license-delete-2.htm");
        httpget("software/license-edit.htm?softwareId=15&licenseId=301");
        httpget("software/license-edit-2.htm");
        httpget("software/list.htm");
        httpget("software/list-export.htm");
        httpget("kb/article-add.htm");
        httpget("kb/article-add-2.htm");
        httpget("kb/article-delete.htm?articleId=22");
        httpget("kb/article-delete-2.htm");
        httpget("kb/article-detail.htm?articleId=22");
        httpget("kb/article-edit.htm?articleId=22");
        httpget("kb/article-edit-2.htm");
        httpget("kb/article-file-add.htm?articleId=22");
        httpget("kb/article-file-add-2.htm");
        httpget("kb/article-file-delete.htm");
        httpget("kb/article-file-delete-2.htm");
        httpget("kb/article-file-download.htm");
        httpget("kb/article-list.htm?categoryId=10");
        httpget("kb/article-print.htm?articleId=22");
        httpget("kb/article-search.htm");
        httpget("kb/category-add.htm");
        httpget("kb/category-add-2.htm");
        httpget("kb/category-edit.htm?categoryId=10");
        httpget("kb/category-edit-2.htm");
        httpget("kb/category-list.htm");
        httpget("kb/index.htm");
        httpget("rss/feed-add.htm");
        httpget("rss/feed-add-2.htm");
        httpget("rss/feed-delete.htm?feedId=7");
        httpget("rss/feed-delete-2.htm");
        httpget("rss/feed-edit.htm?feedId=7");
        httpget("rss/feed-edit-2.htm");
        httpget("rss/feed-list.htm");
        httpget("rss/feed-list-items.htm?feedId=7");
        httpget("rss/feed-list-titles.htm?feedId=7");
        httpget("portal/site-add.htm");
        httpget("portal/site-add-2.htm");
        httpget("portal/site-category-add.htm");
        httpget("portal/site-category-add-2.htm");
        httpget("portal/site-category-edit.htm?categoryId=3");
        httpget("portal/site-category-edit-2.htm");
        httpget("portal/site-category-list.htm");
        httpget("portal/site-delete.htm?siteId=28");
        httpget("portal/site-delete-2.htm");
        httpget("portal/site-detail.htm?siteId=28");
        httpget("portal/site-edit.htm?siteId=28");
        httpget("portal/site-edit-2.htm");
        httpget("portal/site-list.htm");
        httpget("portal/site-list-index.htm");
        httpget("portal/site-list-rss.htm");
        httpget("reports/report-contact.htm");
        httpget("reports/report-contract.htm");
        httpget("reports/report-hardware.htm");
        httpget("reports/report-issue.htm");
        httpget("reports/report-software.htm");
        httpget("reports/report-software-usage.htm");
        httpget("reports/report-type-select.htm");
        httpget("reports/report-search-criteria.htm");
        httpget("reports/report-ouput-select.htm");
        httpget("reports/report-results-export.htm");
        httpget("software/ajax-get-license-custom-fields.htm");
        httpget("software/ajax-get-license-details.htm");
        httpget("software/contact-add.htm?softwareId=15");
        httpget("software/contact-add-2.htm");
        httpget("software/contact-remove-2.htm");
        httpget("software/contacts.htm?softwareId=15");
        httpget("software/custom-fields.htm?softwareId=15");
        httpget("user-preference/contact-edit.htm");
        httpget("user-preference/contact-edit-2.htm");
        httpget("user-preference/index.htm");
        httpget("user-preference/password-edit.htm");
        httpget("user-preference/password-edit-2.htm");
   }

    private void httpget(String endpoint) throws Exception {
        if (!start || endpoint.endsWith("-2.htm")) {
            return;
        }
        new HttpHelper().get("http://localhost:8080/dev/" + endpoint);
    }
}